### ISSUE TITLE
search codebar not found

### ISSUE THREAD

**Issue by guillermohaad** [cconard96/glpi-camerainput-plugin#18]
hi
install the latest version and do the search by barcode but does not find the asset

![image](https://user-images.githubusercontent.com/12921805/151666750-9a4ac99a-8cd3-491c-8c97-18496222c97f.png)

![image](https://user-images.githubusercontent.com/12921805/151666818-0a24a5fe-327e-46b7-a3d4-312ef37f6332.png)

![image](https://user-images.githubusercontent.com/12921805/151666833-6de18db4-dcbb-4df4-a9e0-71af9612c1c7.png)

**Comment by cconard96** [comment]
What is the searched value in the URL of the global search? It may be misdetecting the barcode value.

**Comment by guillermohaad** [comment]
hi, @cconard96 , 
the searched value in the URL of the global search and value is : 788492808274

**Comment by cconard96** [comment]
Odd... if you manually search that number does it work?
The value is right in the URL, so I'm not sure if it is related to the plugin.

This does work for me, but I'm currently using GLPI 10 beta.

**Comment by guillermohaad** [comment]
manually doesn't work either, I'm using the plugin version 1.0.3 GLPI 9.5.5

**Comment by cconard96** [comment]
If manual searching didn't work, then it seems like an issue in GLPI itself. When possible, please try updating to 9.5.7 or 10.0.0 (you may want to wait for the 10.0.1 release).
