### ISSUE TITLE
Plugin fails to install from GLPI Marketplace

### ISSUE THREAD

**Issue by ubrize** [cconard96/glpi-camerainput-plugin#29]
**Describe the bug**
Cannot download the plugin from GLPI Marketplace.

**To Reproduce**
1. Try to install the plugin from GLPI Marketplace
2. See error popup "Error - Unable to download plugin archive."
3. In logs ```Client error: `GET https://github.com/cconard96/glpi-camerainput-plugin/releases/download/v2.1.0/glpi-camerainput-v2.1.0.tar.bz2` resulted in a `404 Not Found` response```

**Screenshots**
![image](https://github.com/cconard96/glpi-camerainput-plugin/assets/7387558/1b71fbaa-fa1e-43f8-8d4c-4344dddc3b50)

**Additional context**
As visible in the log message, the URL to the plugin archive is incorrect. The correct is:
`https://github.com/cconard96/glpi-camerainput-plugin/releases/download/v2.1.0/glpi-camerainput-plugin-2.1.0.tar.bz2` 
When installing from marketplace it tries to load:
`https://github.com/cconard96/glpi-camerainput-plugin/releases/download/v2.1.0/glpi-camerainput-v2.1.0.tar.bz2`

**Comment by cconard96** [comment]
I fixed the URL (no idea why the naming format changed for the last release). I don't know how long it will take to completely update on the server. You can also manually download the release from GitHub and extract to the marketplace folder if you have file access.

**Comment by ubrize** [comment]
Fantastic, thank you! 👍 
I can confirm that it is working now.
