### ISSUE TITLE
glpi-camerainput-plugin crashed GLPI

### ISSUE THREAD

**Issue by RaivoMahnovs** [cconard96/glpi-camerainput-plugin#33]
After copying plugin files into _mysite/glpi/plugins_ folder, server turns error 404. It doesn't even give the opportunity to install the plugin.

1. Copy plugin's files into _yourserver/glpi/plugins_ folder
2. Give the plugin folder proper permissions
3. Refresh server
4. Refresh server address in browser

Expected to see plugins page in browser and install the new plugin.

 - GLPI Server OS: CentOS Stream 9
 - Browser Google Chrome
 - Plugin version 2.1.0

With other plugins there are no problems.

**Comment by cconard96** [comment]
Is the folder inside "glpi/plugins" named "camerainput" exactly?

**Comment by RaivoMahnovs** [comment]
No, it wasn't. I copied it with original name, but now i changed it and it worked fine. Thank you.

**Comment by cconard96** [comment]
If you use the archives in GitHub releases, this should not be an issue. The folder inside the release archives are already named properly.
https://github.com/cconard96/glpi-camerainput-plugin/releases
