### ISSUE TITLE
Install not possible

### ISSUE THREAD

**Issue by DeadpoolFR** [cconard96/glpi-camerainput-plugin#6]
**Describe the bug**
Hi, after manual installation, the plugin is present in "Plugins", but nothing happens when I click on the "Install" icon.

![Sans titre](https://user-images.githubusercontent.com/86774883/124103138-46d55100-da61-11eb-8c9b-bde39f323aed.png)

**System Specifications (please complete the following information):**
PHP Version 7.2.5
Linux / Apache 2
GLPI 9.5.5

**Comment by cconard96** [comment]
You are connected to your GLPI using HTTPS right?
Do you have any errors in the files/_logs/php-errors.log file?

**Comment by DeadpoolFR** [comment]
> You are connected to your GLPI using HTTPS right?
Indeed, I was missing the passage in https for it to be OK, thanks!
