### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by guillermohaad** [cconard96/glpi-camerainput-plugin#7]
hi, Congratulations for your work, excellent plugin, I recommend you develop the following to get more out of it

1- Allow to search for computers by scanning barcode or QR
![image](https://user-images.githubusercontent.com/12921805/126720391-eb1d0be8-e914-49ed-8468-ce649561ee29.png)

2- allow to register bar codes or QR to create new computers or devices

![image](https://user-images.githubusercontent.com/12921805/126720597-d735417d-4c9f-4c6b-b3cd-8c7804be3e37.png)

**Comment by cconard96** [comment]
Hello @guillermohaad.
These are good suggestions. I've added it to the 2.0.0 release milestone tentatively (version for the next major GLPI version) as I consider how to implement and if there are other similar places we can use this feature.

**Comment by guillermohaad** [comment]
@cconard96 Thanks Friend, I congratulate you again and I hope it will be of great help to all

**Comment by cconard96** [comment]
I've added the hook for asset form fields (serial, asset tag (otherserial), and UUID).
These will all be in the 2.0.0 release.

The hook for the search engine hasn't been done yet. The elements for the search engine are difficult to identify in code. This may need a backend change in GLPI but I don't know if it will make it into the GLPI 10 release.

**Comment by cconard96** [comment]
GLPI changes were done and merged for v10:
https://github.com/glpi-project/glpi/pull/10238

I'll start work on integrating this plugin with the Search tonight or over the weekend.

**Comment by cconard96** [comment]
Search integration done in #17. It will be a part of v2.0.0.

**Comment by guillermohaad** [comment]
Hi @cconard96 thank you, We will be attentive and looking forward to this new functionality.
